---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-tests-with-nose
spec:
  steps:
    - name: run-nose-tests
      image: python:3.9
      script: |
        #!/bin/bash
        pip install -r requirements.txt
        pip install nose
        nosetests
